# logging
log_level: 20
# experiment
seed: 0
mlflow_config:
    run_id: ~
    experiment_id: ~
    run_name: lol
    nested: False
    parent_run_id: ~
    tags: ~
    description: ~
    log_system_metrics: ~
sampling_config:
    n_samples: 2
    sample_length: 2
predictors:
    - name: PCA
      model:
          type: nmf
          n_components: 2
    - name: PCA
      model:
          type: pca
          n_components: 2
datasets:
    - name: "Mouse Intestine"
      query_path: "/home/gruengroup/christian/Data/mouse_intestine/intestine_MERFISH.h5ad"
      query_cluster_key: "C_scanvi"
      reference_path: "/home/gruengroup/christian/Projects/notebook_repository/notebooks/data/mouse_small_intestine_sc/mouse_small_intestine_sc.h5ad"
      reference_cluster_key: "cluster"
      min_n_cells_celltype: 2
      n_cells: 2
      max_n_pcs: 2
      max_n_neighbours: 2
