[project]
name = "2026-05-28t07-11-05z"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "nico-wrapper @ git+ssh://git@github.com/gruenlab/nico-wrapper.git@92d037cbc2f2072ecb2a166731932c27d32192be",
    "ipython>=9.13.0",
    "marimo>=0.23.8",
    "pydantic>=2.13.4",
    "pyyaml>=6.0.3",
    "seaborn>=0.13.2",
    "scanpy>=1.11.2",
    "ruff>=0.15.15",
    "altair>=6.1.0",
    "polars>=1.41.1",
]
