#!/bin/bash

set -e


srun \
  --job-name=debug_metabenchmarking \
  --mem=128G \
  --cpus-per-task=8 \
  --gres=gpu:1 \
  --time=02:00:00 \
  --pty \
  uv run ipython --pdb metabenchmarking.py -- -o results_debug.csv
