[project]
name = "2026-06-22t12-32-06z"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.14.1",
    "marimo>=0.23.10",
    "nico2-lib",
    "polars>=1.42.0",
    "pydantic>=2.13.4",
    "pyright>=1.1.410",
    "python-dotenv>=1.2.2",
    "ruff>=0.15.18",
]

[tool.uv.sources]
nico2-lib = { git = "https://github.com/gruenlab/bioinfo-tools.git", subdirectory = "applications/nico2_lib", rev = "96ea3252265fff4f7b7956bcb3fefa0ea17fbf68" }
