n_components: 2
n_samples: 500
seed: 0
n_iterations: 1
scoring_functions:
  - [null, dominic_scoring]
  - [pearson, dominic_scoring]
  - [spearman, dominic_scoring]
  - [cosine_similarity, dominic_scoring]
preprocessing: [identity, log1p]    
database_names:
  - KEGG_2026
  - ARCHS4_Cell-lines
datasets:
  - filepath: /home/gruengroup/christian/Data/mouse_small_intestine_sc.h5ad
    name: mouse_intestine
    cluster_key: cluster
    species: mouse
shuffle_probabilities: [0, 0.2, 0.5, 0.75, 1]
output_csv_path: output.csv
