[project]
name = "2026-05-13t07-33-19z"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "nico2-lib @ git+https://github.com/gruenlab/bioinfo-tools.git@6bc569e134b8ba05e7faf13719bd67ba8cd58e1f#subdirectory=applications/nico2_lib",
    "anndata>=0.12.14",
    "numpy>=2.4.4",
    "scikit-learn>=1.8.0",
    "jupyter>=1.1.1",
    "gseapy>=1.2.1",
    "scanpy>=1.11.2",
    "pydantic>=2.13.4",
    "pyright>=1.1.409",
]
