[project]
name = "2026-05-29t11-37-56z"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "nico2-lib @ git+https://github.com/gruenlab/bioinfo-tools.git@d5684bfdbd219ca11a242d1910a0ed1af65b0259#subdirectory=applications/nico2_lib",
    "altair>=6.1.0",
    "ipython>=9.13.0",
    "marimo>=0.23.8",
    "numpy>=2.4.6",
    "polars>=1.41.1",
    "pydantic>=2.13.4",
    "pyyaml>=6.0.3",
    "ruff>=0.15.15",
    "scanpy>=1.12.1",
    "seaborn>=0.13.2",
    "scikit-learn>=1.8.0",
    "pyright>=1.1.409",
    "sqlmodel>=0.0.38",
    "mlflow>=3.11.1",
    "pyarrow>=23.0.1",
    "pandas>=2.3.3",
    "gseapy>=1.2.1",
]
