n_samples: 5
sample_length: 20
n_pcs: 8
n_neighbours: 6
predictors:
  - name: nmf_3_raw
    model_architecture: nmf
    log_transform: False
    kwargs:
      n_components: 3
  - name: nmf_3_log
    model_architecture: nmf
    log_transform: True
    kwargs:
      n_components: 3
datasets:
  - name: mouse_intestine_spatial
    query_path: ../data/mouse_small_intestine_merfish/mouse_small_intestine_merfish.h5ad
    query_ct_key: "cluster"
    reference_path: ../data/mouse_small_intestine_sc/mouse_small_intestine_sc.h5ad
    reference_ct_key: "cluster"