# logging
log_level: 20
# experiment
seed: 0
mlflow_config:
    run_id: ~
    experiment_id: ~
    run_name: lol
    nested: False
    parent_run_id: ~
    tags: ~
    description: ~
    log_system_metrics: ~
sampling_config:
    n_samples: 4
    panel_size: 500
predictors:
    #- name: MofaFlex (3 components)
    #  scope: celltype
    #  transform: ~
    #  model:
    #      type: mofaflex
    #      n_components: 3
    #- name: MofaFlex (10 components)
    #  scope: global
    #  transform: ~
    #  model:
    #      type: mofaflex
    #      n_components: 3
    - name: Tangram
      scope: global
      transform: ~
      model:
          type: tangram
    #- name: Tangram
    #  scope: celltype
    #  transform: ~
    #  model:
    #      type: tangram
    - name: NMF (3 components)
      scope: celltype
      transform: ~
      model:
          type: nmf
          n_components: 3
    - name: NMF (3 components)
      scope: global
      transform: ~
      model:
          type: nmf
          n_components: 3
    - name: NMF (5 components)
      scope: celltype
      transform: log
      model:
          type: nmf
          n_components: 5
    - name: NMF (5 components)
      scope: global
      transform: log
      model:
          type: nmf
          n_components: 5
    - name: NMF (10 components)
      scope: celltype
      transform: log
      model:
          type: nmf
          n_components: 10
    - name: NMF (10 components)
      scope: global
      transform: ~
      model:
          type: nmf
          n_components: 10
    - name: NMF (Consensus)
      scope: celltype
      transform: ~
      model:
          type: nmf
          n_components: consensus
    #- name: NMF (Consensus)
    #  scope: global
    #  transform: ~
    #  model:
    #      type: nmf
    #      n_components: consensus
    - name: NMF (3 components)
      scope: celltype
      transform: log
      model:
          type: nmf
          n_components: 3
    - name: NMF (3 components)
      scope: global
      transform: log
      model:
          type: nmf
          n_components: 3
    - name: PCA (3 components)
      scope: celltype
      transform: ~
      model:
          type: pca
          n_components: 3
    - name: PCA (3 components)
      scope: global
      transform: ~
      model:
          type: pca
          n_components: 3
    - name: PCA (3 components)
      scope: celltype
      transform: ~
      model:
          type: pca
          n_components: 3
    - name: PCA (3 components)
      scope: global
      transform: ~
      model:
          type: pca
          n_components: 3
    - name: scVI (10 Components)
      scope: global
      transform: ~
      model:
          type: scvi
          n_components: 10
          max_epochs: 200
    #- name: scVI (3 Components)
    #  scope: celltype
    #  transform: ~
    #  model:
    #      type: scvi
    #      n_components: 3
    #      max_epochs: 200
    #- name: scVI (5 Components)
    #  scope: global
    #  transform: ~
    #  model:
    #      type: scvi
    #      n_components: 5
    #      max_epochs: 200
    #- name: scVI (5 Components)
    #  scope: celltype
    #  transform: ~
    #  model:
    #      type: scvi
    #      n_components: 5
    #      max_epochs: 200
    #- name: scVI (10 Components)
    #  scope: global
    #  transform: ~
    #  model:
    #      type: scvi
    #      n_components: 10
    #      max_epochs: 200
    #- name: scVI (10 Components)
    #  scope: celltype
    #  transform: ~
    #  model:
    #      type: scvi
    #      n_components: 10
    #      max_epochs: 200
datasets:
    - name: "Mouse Intestine"
      path: "/home/gruengroup/christian/Projects/notebook_repository/notebooks/data/mouse_small_intestine_sc/mouse_small_intestine_sc.h5ad"
      cluster_key: "cluster"
      min_n_cells_per_celltype: 20
      n_cells: ~
      max_n_pcs: 10
      max_n_neighbours: 6
      remove_constant_features: true
    - name: Andy Heart
      path: /home/gruengroup/christian/Data/benchmark_sample_data/andy_reference_downsampled.h5ad
      cluster_key: "simple_annot"
      min_n_cells_per_celltype: 20
      n_cells: 5000
      max_n_pcs: 10
      max_n_neighbours: 6
      remove_constant_features: true
    - name: Jennifer Spatial
      path: /home/gruengroup/christian/Data/benchmark_sample_data/jennifer_reference_downsampled.h5ad
      cluster_key: cell_type
      min_n_cells_per_celltype: 20
      n_cells: 2500
      max_n_pcs: 10
      max_n_neighbours: 6
      remove_constant_features: true
